### ISSUE TITLE
checklist of stat and geom layers to adapt to biplots

### ISSUE THREAD

**Issue by corybrunson** [corybrunson/ordr#62]
This issue will collect stat, geom, or other layers implemented in other packages (noted unless {ggplot2} itself) that should be adapted to `ggbiplot()` layers. Cognominal stats and geoms are listed with the stats. See #61 for the list of needed but not-yet-implemented layers.

Statistical transformations (`stat`s):
- [ ] `StatBin2d`, `StatBinHex`
- [ ] `StatDensity2d`
- [ ] `StatPointdensity` from [{ggpointdensity}](https://github.com/LKremer/ggpointdensity)
- [ ] `StatHdr`, `StatHdrLines`, `StatHdrPoints`, `StatHdrRug` from [{ggdensity}](https://github.com/jamesotto852/ggdensity)
- [ ] `StatVoronoi` from [{ggvoronoi}](https://github.com/garretrc/ggvoronoi)

Geometric elements (`geom`s):
- [ ] `GeomPointTrace` and `GeomPathTrace` from [{ggtrace}](https://github.com/rnabioco/ggtrace)

Layers for 1-dimensional biplots:
- [ ] `PositionStack` (`stat = "align"`) for stacking variable axes or vectors
- [ ] `StatDensity`, `GeomDotplot`, `GeomHistogram`, `GeomRug`
